from . import test_api_actions
from . import test_api_configuration
from . import test_api_pagination
from . import test_baseline
from . import test_bosta_api_client
from . import test_configuration_security
from . import test_delivery_models
from . import test_delivery_security
from . import test_phase3_baseline
from . import test_api_normalization
from . import test_api_extraction
from . import test_phase4_baseline
from . import test_real_bosta_payload_shapes
from . import test_persistence_service
from . import test_sync_service
from . import test_phase5_baseline
from . import test_lifecycle_interpreter
from . import test_lifecycle_persistence
from . import test_phase6_baseline
from . import test_product_code_parser
from . import test_product_tester_links
from . import test_product_mapping
from . import test_inventory_effects
from . import test_inventory_idempotency
from . import test_phase7_baseline
from . import test_phase7_sync_integration
from . import test_return_restoration
from . import test_phase8_baseline
from . import test_phase8_sync_integration
